# Generated by Django 4.0 on 2022-01-03 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover',
            field=models.ImageField(default='covers/default.png', upload_to='covers/'),
        ),
    ]
